title: My Site
description: Something, something, description

plugins:
- jekyll-remote-theme

remote_theme: daviddarnes/alembic@main

navigation_pages: false

navigation:
- label: Home
  url: /
- label: About
  url: /about/
- label: Projects
  url: /projects/
